const UserActionTypes = {
  SET_CURRENT_USER: "SET_CURRENT_USER",
  ADD_PLAN_START: "ADD_PLAN_START",
  ADD_PLAN_SUCCESS: "ADD_PLAN_SUCCESS",
  ADD_PLAN_FAIL: "ADD_PLAN_FAIL"
};

export default UserActionTypes;
